export enum AppTypes {
    SET_INITIALIZED = 'SET_INITIALIZED',
}

export enum AuthTypes {
    SET_AUTH_USER_DATA = 'SET_AUTH_DATA',
    SET_AUTH_ERROR = 'SET_AUTH_ERROR',
    SET_CAPTCHA_URL = 'SET_CAPTCHA_URL',
}

export enum DialogsTypes {
    ADD_MESSAGE = 'ADD_MESSAGE',
    UPDATE_NEW_MESSAGE_BODY = 'UPDATE_NEW_MESSAGE_BODY',
}

export enum ProfileTypes {
    ADD_POST = 'ADD_POST',
    UPDATE_NEW_POST_BODY = 'UPDATE_NEW_POST_BODY',
    SET_PROFILE = 'SET_PROFILE',
    SET_STATUS = 'SET_STATUS',
}

export enum UsersTypes {
    FOLLOW = 'FOLLOW',
    UNFOLLOW = 'UNFOLLOW',
    SET_USERS = 'SET_USERS',
    SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT',
    SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
    TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING',
}

